### PR TITLE
remove k8s.node.* metrics remapping

### PR DESCRIPTION
**Pull request by tetianakravchenko**

### CODE REVIEW

**Review by gizas — APPROVED** [review]

**Review by ChrsMark — APPROVED** [review]

**Comment by ChrsMark** [comment]
Interestingly merging is blocked on approval(+merge?) from @elastic/obs-infraobs-integrations. However by looking into this group I wonder if that makes sense since most of the people are not really involved with the OTel initiative at the moment? 
So @AlexanderWert would that make sense to give permissions to @elastic/otel-devs as well as make @tetianakravchenko and @gizas owners/approves of the k8s part?

**Review by lahsivjar — APPROVED** [review]
Thanks for the quick fix.

**Comment by AlexanderWert** [comment]
> So @AlexanderWert would that make sense to give permissions to @elastic/otel-devs as well as make @tetianakravchenko and @gizas owners/approves of the k8s part?

yes absolutely! I just don't have the permissions on this repo. @elastic/observablt-robots Can you please give @elastic/otel-devs maintainer rights on this?

**Comment by reakaleek** [comment]
> > So @AlexanderWert would that make sense to give permissions to @elastic/otel-devs as well as make @tetianakravchenko and @gizas owners/approves of the k8s part?
> 
> yes absolutely! I just don't have the permissions on this repo. @elastic/observablt-robots Can you please give @elastic/otel-devs maintainer rights on this?

When https://github.com/elastic/catalog-info/pull/1236 is merged and if the next terrazzo build succeeds, then @elastic/otel-devs should be maintainers

**Pull request merged**
